### ISSUE TITLE
Parse controls from resource file

### ISSUE THREAD

**Issue by addonovan** [addonovan/freevicky#3]
Controls should be able to be generated dynamically from resources located in the `res/gfx/ui` folder. This is to make modifications and to allow for easier modifications in the future.

The ui files should be written in yaml and probably could be parsed using [yaml-cpp](https://github.com/jbeder/yaml-cpp). Elements should start by identifying their type (image, label, button, etc), then define other properties. For interactive elements (like button), actions might be the name of the source file, then the method name within the file; however, that might change depending on the implementation of lua.

For example, this will describe two buttons: one at the origin with the text "Do it" that's a regular button, that will "do it", and the other positioned underneath it with the text "Don't" that's a cancel button.

```yaml
- button:
  text: "Do it"
  position: [ 0, 0 ]
  design: button_long
  action: [ "does_action", "does_he_do_it( true )" ]

- button:
  text: "Don't"
  position: [ 0, 32 ]
  design: button_long_cancel
  action: [ "does_action", "does_he_do_it( false )" ]
```

Some basic properties that should be implemented by the parser:
* `text: String`
* `position: Pair< Int, Int >`
* `design: String`
   * The design will just be the base name of the files associated with the button, there may be other types associated with it, for instance, a file that matches `$base_hover` will be displayed when the control is hovered over.
* `action: Pair< String, String >`
   * The first string should be the name of the lua file from the `scripts` directory containing the method.
      * The file can be preceded with the directory if the lua file isn't in the root scripts dir.
      * The existence of this file should be checked when the action attribute is parsed, and an exception should be thrown if it doesn't exist.

Other properties will most definitely be added later, but these should give a basic, but functional UI system at the very least.
